
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::TestAppCairo.SealControl sealcontrol1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.sealcontrol1 = new global::TestAppCairo.SealControl ();
		this.sealcontrol1.Name = "sealcontrol1";
		this.Add (this.sealcontrol1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
